items_db = [
    {"id": 1, "name": "Alice", "description": "User from New York", "created_by": 2},
    {
        "id": 2,
        "name": "Book A",
        "description": "Introduction to Python",
        "created_by": 1,
    },
    {"id": 3, "name": "Laptop", "description": "15-inch display", "created_by": 2},
    {"id": 4, "name": "Pen", "description": "Blue ink ballpoint", "created_by": 3},
    {
        "id": 5,
        "name": "Chair",
        "description": "Ergonomic office chair",
        "created_by": 2,
    },
    {"id": 6, "name": "Table", "description": "Wooden dining table", "created_by": 1},
    {"id": 7, "name": "Bob", "description": "Admin account", "created_by": 2},
    {"id": 8, "name": "Notebook", "description": "200 pages ruled", "created_by": 2},
    {"id": 9, "name": "Phone", "description": "Android device", "created_by": 1},
    {"id": 10, "name": "Monitor", "description": "27-inch 4K", "created_by": 1},
    {
        "id": 11,
        "name": "Headphones",
        "description": "Noise cancelling",
        "created_by": 2,
    },
    {"id": 12, "name": "Backpack", "description": "Water-resistant", "created_by": 1},
    {"id": 13, "name": "Keyboard", "description": "Mechanical keys", "created_by": 3},
    {"id": 14, "name": "Mouse", "description": "Wireless optical", "created_by": 3},
    {"id": 15, "name": "Camera", "description": "DSLR with 50mm lens", "created_by": 3},
    {
        "id": 16,
        "name": "Shoes",
        "description": "Running shoes size 10",
        "created_by": 2,
    },
    {"id": 17, "name": "Bottle", "description": "1L stainless steel", "created_by": 3},
    {
        "id": 18,
        "name": "Fan",
        "description": "Ceiling fan with remote",
        "created_by": 3,
    },
    {"id": 19, "name": "Couch", "description": "3-seater leather", "created_by": 1},
    {"id": 20, "name": "Lamp", "description": "Desk lamp with LED", "created_by": 2},
]


users_db = [
    {
        "id": 1,
        "name": "Alice Johnson",
        "email": "alice.j@example.com",
        "is_active": False,
    },
    {
        "id": 2,
        "name": "Bob Smith",
        "email": "bob.smith@example.com",
        "is_active": False,
    },
    {
        "id": 3,
        "name": "Charlie Davis",
        "email": "charlie.d@example.com",
        "is_active": False,
    },
    {
        "id": 4,
        "name": "Diana Moore",
        "email": "diana.moore@example.com",
        "is_active": False,
    },
    {
        "id": 5,
        "name": "Ethan Clark",
        "email": "ethan.c@example.com",
        "is_active": False,
    },
    {
        "id": 6,
        "name": "Fiona Wright",
        "email": "fiona.w@example.com",
        "is_active": True,
    },
    {
        "id": 7,
        "name": "George Lopez",
        "email": "george.lopez@example.com",
        "is_active": True,
    },
    {
        "id": 8,
        "name": "Hannah Lee",
        "email": "hannah.lee@example.com",
        "is_active": False,
    },
    {"id": 9, "name": "Ian Walker", "email": "ian.w@example.com", "is_active": True},
    {"id": 10, "name": "Jenna Hall", "email": "jenna.h@example.com", "is_active": True},
    {
        "id": 11,
        "name": "Kevin Young",
        "email": "kevin.y@example.com",
        "is_active": False,
    },
    {
        "id": 12,
        "name": "Laura Green",
        "email": "laura.g@example.com",
        "is_active": False,
    },
    {
        "id": 13,
        "name": "Mark Turner",
        "email": "mark.t@example.com",
        "is_active": False,
    },
    {"id": 14, "name": "Nina Scott", "email": "nina.s@example.com", "is_active": True},
    {
        "id": 15,
        "name": "Oliver King",
        "email": "oliver.k@example.com",
        "is_active": False,
    },
    {
        "id": 16,
        "name": "Paula Adams",
        "email": "paula.a@example.com",
        "is_active": False,
    },
    {
        "id": 17,
        "name": "Quentin Baker",
        "email": "quentin.b@example.com",
        "is_active": True,
    },
    {
        "id": 18,
        "name": "Rachel Reed",
        "email": "rachel.r@example.com",
        "is_active": True,
    },
    {"id": 19, "name": "Sam Carter", "email": "sam.c@example.com", "is_active": True},
    {"id": 20, "name": "Tina Evans", "email": "tina.e@example.com", "is_active": False},
]
